#!/usr/bin/env bash
set -euo pipefail

# Build deterministic distributable registry files from package source definitions.

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
readonly CONFIG_FILE="${REPO_ROOT}/registry.config.yaml"
readonly REGISTRY_FILE="${REPO_ROOT}/registry.yaml"
readonly PYTHON_RENDERER="${SCRIPT_DIR}/render_mise.py"

require_command() {
  local -r command_name="$1"
  if ! command -v "${command_name}" >/dev/null 2>&1; then
    printf 'error: required command not found: %s\n' "${command_name}" >&2
    exit 127
  fi
}

require_command yq
require_command python3

readonly TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/aqua-registry-build.XXXXXXXX")"
trap 'rm -rf -- "${TEMP_DIR}"' EXIT

readonly MERGED_YAML="${TEMP_DIR}/registry.body.yaml"
readonly CONFIG_JSON="${TEMP_DIR}/config.json"
readonly REGISTRY_JSON="${TEMP_DIR}/registry.json"
readonly MISE_OUTPUT_TMP="${TEMP_DIR}/mise.registry.toml"

PACKAGE_FILES=()
if [[ -d "${REPO_ROOT}/pkgs" ]]; then
  mapfile -d '' PACKAGE_FILES < <(
    find "${REPO_ROOT}/pkgs" -type f -name registry.yaml -print0 | sort -z
  )
fi

for package_file in "${PACKAGE_FILES[@]}"; do
  if [[ "$(yq -r '.packages | type' "${package_file}")" != '!!seq' ]]; then
    printf 'error: %s must contain a packages sequence\n' "${package_file}" >&2
    exit 1
  fi

  if [[ "$(yq -r '[.packages[] | select((.name // "") == "" or (.type // "") == "")] | length' "${package_file}")" != '0' ]]; then
    printf 'error: every package in %s requires non-empty name and type fields\n' "${package_file}" >&2
    exit 1
  fi
done

if (( ${#PACKAGE_FILES[@]} == 0 )); then
  printf 'packages: []\n' > "${MERGED_YAML}"
else
  yq ea -o=yaml \
    '. as $item ireduce ({"packages": []}; .packages += ($item.packages // [])) | .packages |= sort_by(.name)' \
    "${PACKAGE_FILES[@]}" > "${MERGED_YAML}"
fi

readonly DUPLICATE_NAMES="$({ yq -r '.packages[].name' "${MERGED_YAML}" || true; } | sort | uniq -d)"
if [[ -n "${DUPLICATE_NAMES}" ]]; then
  printf 'error: duplicate Aqua package names detected:\n%s\n' "${DUPLICATE_NAMES}" >&2
  exit 1
fi

{
  printf '%s\n' '# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json'
  printf '%s\n' '# GENERATED by scripts/build.sh. Do not edit manually.'
  cat "${MERGED_YAML}"
} > "${TEMP_DIR}/registry.yaml"

mv -- "${TEMP_DIR}/registry.yaml" "${REGISTRY_FILE}"

yq -o=json '.' "${CONFIG_FILE}" > "${CONFIG_JSON}"
yq -o=json '.' "${REGISTRY_FILE}" > "${REGISTRY_JSON}"

readonly MISE_GENERATE="$(yq -r '.mise.generate // true' "${CONFIG_FILE}")"
if [[ "${MISE_GENERATE}" == 'true' ]]; then
  readonly MISE_OUTPUT_REL="$(yq -r '.mise.output // "mise/registry.toml"' "${CONFIG_FILE}")"
  if [[ "${MISE_OUTPUT_REL}" = /* || "${MISE_OUTPUT_REL}" == *'..'* ]]; then
    printf 'error: mise.output must be a repository-relative path without ..\n' >&2
    exit 1
  fi

  python3 "${PYTHON_RENDERER}" \
    --config "${CONFIG_JSON}" \
    --registry "${REGISTRY_JSON}" \
    --output "${MISE_OUTPUT_TMP}"

  readonly MISE_OUTPUT="${REPO_ROOT}/${MISE_OUTPUT_REL}"
  mkdir -p -- "$(dirname -- "${MISE_OUTPUT}")"
  mv -- "${MISE_OUTPUT_TMP}" "${MISE_OUTPUT}"
fi
