#!/usr/bin/env python3
"""Render a mise config fragment from repository configuration and Aqua registry JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser()
  parser.add_argument("--config", required=True, type=Path)
  parser.add_argument("--registry", required=True, type=Path)
  parser.add_argument("--output", required=True, type=Path)
  return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
  with path.open("r", encoding="utf-8") as handle:
    value = json.load(handle)
  if not isinstance(value, dict):
    raise ValueError(f"{path}: expected a JSON object")
  return value


def toml_string(value: str) -> str:
  return json.dumps(value, ensure_ascii=False)


def derive_registry_url(config: dict[str, Any]) -> str:
  repository = config.get("repository", {})
  explicit = str(repository.get("public_url", "")).strip()
  if explicit:
    return explicit.rstrip("/")

  provider = str(repository.get("provider", "github"))
  owner = str(repository.get("owner", "")).strip()
  name = str(repository.get("name", "")).strip()
  if provider != "github":
    raise ValueError(
      "repository.public_url is required when repository.provider is not 'github'"
    )
  if not owner or not name:
    raise ValueError("repository.owner and repository.name must be configured")
  return f"https://github.com/{owner}/{name}"


def build_aliases(
  config: dict[str, Any], registry: dict[str, Any]
) -> dict[str, str]:
  mise = config.get("mise", {})
  strategy = str(mise.get("alias_strategy", "basename"))
  if strategy not in {"basename", "none"}:
    raise ValueError("mise.alias_strategy must be 'basename' or 'none'")

  raw_overrides = mise.get("alias_overrides", {}) or {}
  raw_excludes = mise.get("alias_excludes", []) or []
  if not isinstance(raw_overrides, dict):
    raise ValueError("mise.alias_overrides must be a mapping")
  if not isinstance(raw_excludes, list):
    raise ValueError("mise.alias_excludes must be a list")

  overrides = {str(key): str(value) for key, value in raw_overrides.items()}
  excludes = {str(value) for value in raw_excludes}
  packages = registry.get("packages", []) or []
  if not isinstance(packages, list):
    raise ValueError("registry packages must be a list")

  aliases: dict[str, str] = {}
  alias_owner: dict[str, str] = {}

  for package in packages:
    if not isinstance(package, dict):
      raise ValueError("every package must be a mapping")
    package_name = str(package.get("name", "")).strip()
    if not package_name:
      raise ValueError("every package must have a non-empty name")
    if package_name in excludes:
      continue

    alias = overrides.get(package_name)
    if alias is None:
      if strategy == "none":
        continue
      alias = package_name.rsplit("/", maxsplit=1)[-1]

    alias = alias.strip()
    if not alias:
      raise ValueError(f"empty mise alias for {package_name}")
    if "@" in alias or ":" in alias:
      raise ValueError(
        f"mise alias {alias!r} for {package_name} must not contain '@' or ':'"
      )

    previous = alias_owner.get(alias)
    if previous is not None and previous != package_name:
      raise ValueError(
        f"mise alias collision: {alias!r} is generated for both "
        f"{previous!r} and {package_name!r}; configure an alias override or exclusion"
      )

    alias_owner[alias] = package_name
    aliases[alias] = f"aqua:{package_name}"

  return dict(sorted(aliases.items()))


def render(config: dict[str, Any], registry: dict[str, Any]) -> str:
  mise = config.get("mise", {})
  registry_url = derive_registry_url(config)
  cache_ttl = str(mise.get("registry_cache_ttl", "1w"))
  aliases = build_aliases(config, registry)

  lines = [
    "# GENERATED by scripts/build.sh. Do not edit manually.",
    "# Install this as a mise config fragment to expose prefix-free aliases.",
    "",
    "[settings]",
    f"aqua.registries = [{toml_string(registry_url)}]",
    f"aqua.registry_cache_ttl = {toml_string(cache_ttl)}",
    "",
    "[tool_alias]",
  ]
  lines.extend(
    f"{toml_string(alias)} = {toml_string(backend)}"
    for alias, backend in aliases.items()
  )
  return "\n".join(lines) + "\n"


def main() -> int:
  args = parse_args()
  config = read_json(args.config)
  registry = read_json(args.registry)
  args.output.parent.mkdir(parents=True, exist_ok=True)
  args.output.write_text(render(config, registry), encoding="utf-8", newline="\n")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
